"""
email_service.py — Send email via Gmail SMTP (TLS).
Falls back to mock mode if credentials are not configured.
"""
from __future__ import annotations

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from app.config import get_settings

log = logging.getLogger(__name__)


def send_email(
    recipient: str,
    subject: str,
    message: str,
    html_body: str | None = None,
) -> dict:
    """
    Send an email.

    Returns
    -------
    dict  with keys: status ("sent" | "mock" | "failed"), detail
    """
    cfg = get_settings()

    if not cfg.SMTP_USER or not cfg.SMTP_PASS:
        log.warning("[email_service] SMTP not configured → mock mode")
        return {
            "status": "mock",
            "detail": f"[MOCK] Email to {recipient} | subject={subject} | body={message[:80]}",
        }

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = f"Notification Bot <{cfg.SMTP_USER}>"
        msg["To"] = recipient

        # Plain text fallback
        msg.attach(MIMEText(message, "plain", "utf-8"))

        # HTML part (richer version if provided)
        body_html = html_body or _default_html(subject, message)
        msg.attach(MIMEText(body_html, "html", "utf-8"))

        with smtplib.SMTP(cfg.SMTP_HOST, cfg.SMTP_PORT, timeout=15) as server:
            server.ehlo()
            server.starttls()
            server.login(cfg.SMTP_USER, cfg.SMTP_PASS)
            server.sendmail(cfg.SMTP_USER, [recipient], msg.as_string())

        log.info("[email_service] Sent to %s", recipient)
        return {"status": "sent", "detail": f"Email delivered to {recipient}"}

    except smtplib.SMTPAuthenticationError:
        log.error("[email_service] Authentication failed. Check SMTP_USER/SMTP_PASS.")
        return {"status": "failed", "detail": "SMTP authentication error"}
    except Exception as exc:
        log.exception("[email_service] Unexpected error")
        return {"status": "failed", "detail": str(exc)}


def _default_html(subject: str, message: str) -> str:
    return f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="font-family:Inter,Arial,sans-serif;background:#f4f6f9;padding:32px;margin:0">
  <div style="max-width:600px;margin:0 auto;background:#ffffff;border-radius:10px;
              padding:32px;border:1px solid #e2e8f0">
    <h2 style="color:#1a202c;margin:0 0 8px">{subject}</h2>
    <hr style="border:none;border-top:1px solid #e2e8f0;margin:16px 0">
    <p style="color:#4a5568;font-size:15px;line-height:1.7">{message}</p>
    <hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0 12px">
    <p style="color:#a0aec0;font-size:11px;margin:0">
      Auto-generated by Notification Service API · Do not reply
    </p>
  </div>
</body>
</html>"""
